"""add_activities_table

Revision ID: 64cad042c585
Revises: 0003_add_activities_table
Create Date: 2026-04-20 12:52:28.605449
"""
from alembic import op
import sqlalchemy as sa


revision = '64cad042c585'
down_revision = '0003_add_activities_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interview_sessions_candidate_id_key', 'interview_sessions', type_='unique')
    op.drop_index('ix_interview_sessions_candidate_id', table_name='interview_sessions')
    op.create_index(op.f('ix_interview_sessions_candidate_id'), 'interview_sessions', ['candidate_id'], unique=True)
    op.drop_constraint('resume_scores_candidate_id_key', 'resume_scores', type_='unique')
    op.drop_index('ix_resume_scores_candidate_id', table_name='resume_scores')
    op.create_index(op.f('ix_resume_scores_candidate_id'), 'resume_scores', ['candidate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_scores_candidate_id'), table_name='resume_scores')
    op.create_index('ix_resume_scores_candidate_id', 'resume_scores', ['candidate_id'], unique=False)
    op.create_unique_constraint('resume_scores_candidate_id_key', 'resume_scores', ['candidate_id'])
    op.drop_index(op.f('ix_interview_sessions_candidate_id'), table_name='interview_sessions')
    op.create_index('ix_interview_sessions_candidate_id', 'interview_sessions', ['candidate_id'], unique=False)
    op.create_unique_constraint('interview_sessions_candidate_id_key', 'interview_sessions', ['candidate_id'])
    # ### end Alembic commands ###
