"""add_interviews_table

Revision ID: f3e1d3bca47e
Revises: 8b7db6d58c10
Create Date: 2026-04-21 16:43:02.752001
"""
from alembic import op
import sqlalchemy as sa


revision = 'f3e1d3bca47e'
down_revision = '8b7db6d58c10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_interviews_token', 'interviews', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_interviews_token', 'interviews', ['token'])
    # ### end Alembic commands ###
